# general settings
name: 000_BSRN_x4_C64B8_L1_1000k
model_type: SRModel
scale: 4
num_gpu: 8  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: /mnt/petrelfs/puyuandong/Low_level_vision/BSRN_Distillation/datasets/Classical/DF2K/DF2K_train_HR_sub.lmdb
    dataroot_lq: /mnt/petrelfs/puyuandong/Low_level_vision/BSRN_Distillation/datasets/Classical/DF2K/DF2K_train_LR_bicubic_X4_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: ./datasets/Classical/Set5/GTmod4
    dataroot_lq: ./datasets/Classical/Set5/LRbicx4
    io_backend:
      type: disk
  val_2:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: /mnt/petrelfs/puyuandong/Low_level_vision/dataset/DIV2K/valid/DIV2K_valid_HR
    dataroot_lq: /mnt/petrelfs/puyuandong/Low_level_vision/dataset/DIV2K/valid/DIV2K_valid_lr/X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

# network structures
network_g:
  type: BSRN
  num_in_ch: 3
  num_feat: 64
  num_block: 8
  num_out_ch: 3
  upscale: 4
  conv: BSConvU

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: /mnt/petrelfs/puyuandong/Low_level_vision/BSRN_Distillation/experiments/000_BSRN_x4_C64B8_L1_1000k/training_states/440000.state

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [1000000]
    restart_weights: [1]
    eta_min: !!float 1e-7


  total_iter: 1000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e4
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~
    entity: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500