# GENERATE TIME: Wed Apr 13 23:32:24 2022
# CMD:
# basicsr/train.py -opt options/train/RFDN/ablation_RFDN_x4.yml

# GENERATE TIME: Mon Mar  7 10:54:03 2022
# CMD:
# basicsr/train.py -opt options/train/RFDN/train_RFDN_x4.yml

# Modified SRResNet w/o BN from:
# Photo-Realistic Single Image Super-Resolution Using a Generative Adversarial Network

# general settings
name: B001_RFDN-BSConvU_L1_500k
model_type: SRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
#    dataroot_gt: /mnt/yxsun/Project/Data/datasets/DIV2K/DIV2K_train_HR_sub
#    dataroot_lq: /mnt/yxsun/Project/Data/datasets/DIV2K/DIV2K_train_LR_bicubic/X4_sub
#    (for lmdb)
    dataroot_gt: ./datasets/DF2K/DF2K_train_HR_sub.lmdb
    dataroot_lq: ./datasets/DF2K/DF2K_train_LR_bicubic_X4_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: lmdb
      # (for lmdb)
      # type: lmdb

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 3
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: DIV2K_val
    type: PairedImageDataset
    dataroot_gt: ./datasets/DIV2K/DIV2K_valid_HR/
    dataroot_lq: ./datasets/DIV2K/DIV2K_valid_LR_bicubic/X4/
    io_backend:
      type: disk

# network structures
network_g:
  type: BSRNB4
  num_in_ch: 3
  num_feat: 50
  num_block: 4
  num_out_ch: 3
  upscale: 4
  conv: BSConvU

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [400000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 400000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: NTIRE2022_Ablation
    # project: ~
    resume_id: ~
    # entity: ~
    entity: xpixel-ntire2022

# dist training settings
dist_params:
  backend: nccl
  port: 29500
